### ISSUE TITLE
sliding windows inference for binary classification problem

### ISSUE THREAD

**Issue by lilipj** [Project-MONAI/tutorials#321] opened 2021-08-25 09:39 UTC
Is it possible to use the sliding windows inference for a classification problem (2d)?
I'm getting an error when the prediction dimension is different from the image dimension :

RuntimeError: The size of tensor a (128) must match the size of tensor b (2) at non-singleton dimension 1
 
with : size of sliding windows = 128, and the size of the tensor prediction = 2.

Thanks in advance.

**Comment by wyli** [comment] 2021-08-25 09:45
Is this a duplicate of https://github.com/Project-MONAI/MONAI/discussions/1706? Please use that discussion tab. The issue list here is for reporting bugs and requesting specific features

**Comment by Nic-Ma** [comment] 2021-08-25 09:46
Hi @lilipj ,

And could you please help provide your full test program for further analysis?
I think it should be related to some data shape issue, please make sure your `image` and `label` are `CHWD` shape(use `EnsureChannelFirstd` transform for them).

Thanks.

**Closed by wyli** 2021-08-25 09:45 UTC
