### ISSUE TITLE
Need keepTopKConnectedComponent 

### ISSUE THREAD

**Issue by cvlearn913** [Project-MONAI/tutorials#593] opened 2022-03-02 07:52 UTC
When I was extracting the connected component, I found that Monai seemed to be able to extract only the largest connected component.
There were no problems with the single-organ, but when it comes to kidney which is paird organ, after executing the `monai.transforms.KeepLargestConnectedComponent)` it will loss a apart of it.

![image](https://user-images.githubusercontent.com/59678550/156318088-797a586d-650f-49ab-a8b1-eae31d2232ca.png)

![image](https://user-images.githubusercontent.com/59678550/156318280-8b07468b-10fc-482e-b0ed-fe36168142f1.png)

**Comment by rijobro** [comment] 2022-03-02 09:25
Agree this is important but closing as a duplicate of https://github.com/Project-MONAI/MONAI/issues/3809.

**Closed by rijobro** 2022-03-02 09:25 UTC
