### ISSUE TITLE
cron test error: PyTorch_Lightning/metrics

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#530] opened 2022-02-02 21:57 UTC
**Describe the bug**
```
Running ./modules/TorchIO_MONAI_PyTorch_Lightning.ipynb
Checking PEP8 compliance...
Running notebook...
/opt/conda/lib/python3.8/site-packages/papermill/iorw.py:58: FutureWarning: pyarrow.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
  from pyarrow import HadoopFileSystem

Executing:   0%|          | 0/35 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/35 [00:01<00:44,  1.32s/cell]
Executing:  11%|█▏        | 4/35 [00:05<00:43,  1.42s/cell]
Executing:  14%|█▍        | 5/35 [00:20<02:33,  5.13s/cell]
Executing:  17%|█▋        | 6/35 [00:23<02:14,  4.65s/cell]
Executing:  17%|█▋        | 6/35 [00:24<01:59,  4.11s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [3]":
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_11976/1107065518.py in <module>
      7 import pandas as pd
      8 import torchio as tio
----> 9 import pytorch_lightning as pl
     10 import matplotlib.pyplot as plt
     11 import seaborn as sns

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/__init__.py in <module>
     26 _PROJECT_ROOT = os.path.dirname(_PACKAGE_ROOT)
     27 
---> 28 from pytorch_lightning import metrics  # noqa: E402
     29 from pytorch_lightning.callbacks import Callback  # noqa: E402
     30 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.metrics.classification import (  # noqa: F401
     15     Accuracy,
     16     AUC,

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
     15 from pytorch_lightning.metrics.classification.auc import AUC  # noqa: F401
     16 from pytorch_lightning.metrics.classification.auroc import AUROC  # noqa: F401

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py in <module>
     16 import torch
     17 
---> 18 from pytorch_lightning.metrics.functional.accuracy import _accuracy_compute, _accuracy_update
     19 from pytorch_lightning.metrics.metric import Metric
     20 

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/functional/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.metrics.functional.accuracy import accuracy  # noqa: F401
     15 from pytorch_lightning.metrics.functional.auc import auc  # noqa: F401
     16 from pytorch_lightning.metrics.functional.auroc import auroc  # noqa: F401

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/functional/accuracy.py in <module>
     16 import torch
     17 
---> 18 from pytorch_lightning.metrics.classification.helpers import _input_format_classification, DataType
     19 
     20 

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/helpers.py in <module>
     17 import torch
     18 
---> 19 from pytorch_lightning.metrics.utils import select_topk, to_onehot
     20 from pytorch_lightning.utilities import LightningEnum
     21 

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/utils.py in <module>
     16 import torch
     17 
---> 18 from pytorch_lightning.utilities import rank_zero_warn
     19 
     20 METRIC_EPS = 1e-6

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/__init__.py in <module>
     16 import numpy
     17 
---> 18 from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
     19 from pytorch_lightning.utilities.distributed import (  # noqa: F401
     20     AllGatherGrad,

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py in <module>
     27 if _TORCHTEXT_AVAILABLE:
     28     if _compare_version("torchtext", operator.ge, "0.9.0"):
---> 29         from torchtext.legacy.data import Batch
     30     else:
     31         from torchtext.data import Batch

ModuleNotFoundError: No module named 'torchtext.legacy'
```

**Comment by wyli** [comment] 2022-02-05 18:29
could you help look into this one? @Nic-Ma

**Comment by Nic-Ma** [comment] 2022-02-06 03:11
Sure, I will check it soon.

Thanks for your reminder.

**Comment by Nic-Ma** [comment] 2022-02-07 10:14
This root cause of this issue is fixed with PyTorch Lightning PR: https://github.com/PyTorchLightning/pytorch-lightning/pull/10724.
Let's temporarily use the fixed PyTorch version to avoid the issue until PyTorchLightning releases new version: https://github.com/Project-MONAI/tutorials/pull/539.

Thanks.

**Comment by akihironitta** [comment] 2022-02-07 19:01
Hi @Nic-Ma, `pytorch-lightning==1.5.10` will include the patch and should be released this week (tomorrow or in a few days).

**Comment by wyli** [comment] 2022-02-08 09:13
this is still an issue with a different error:
```
real	0m40.583s
user	0m44.935s
sys	0m16.507s
Running ./modules/TorchIO_MONAI_PyTorch_Lightning.ipynb
Checking PEP8 compliance...
Running notebook...
/opt/conda/lib/python3.8/site-packages/papermill/iorw.py:58: FutureWarning: pyarrow.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
  from pyarrow import HadoopFileSystem

Executing:   0%|          | 0/37 [00:00<?, ?cell/s]
Executing:   3%|▎         | 1/37 [00:01<00:45,  1.26s/cell]
Executing:  11%|█         | 4/37 [00:05<00:44,  1.35s/cell]
Executing:  16%|█▌        | 6/37 [01:01<06:44, 13.04s/cell]
Executing:  19%|█▉        | 7/37 [01:20<07:10, 14.35s/cell]
Executing:  22%|██▏       | 8/37 [01:23<05:35, 11.57s/cell]
Executing:  22%|██▏       | 8/37 [01:24<05:05, 10.55s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_11722/1107065518.py in <module>
      7 import pandas as pd
      8 import torchio as tio
----> 9 import pytorch_lightning as pl
     10 import matplotlib.pyplot as plt
     11 import seaborn as sns

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/__init__.py in <module>
     18 _PROJECT_ROOT = os.path.dirname(_PACKAGE_ROOT)
     19 
---> 20 from pytorch_lightning.callbacks import Callback  # noqa: E402
     21 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402
     22 from pytorch_lightning.trainer import Trainer  # noqa: E402

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.callbacks.base import Callback
     15 from pytorch_lightning.callbacks.device_stats_monitor import DeviceStatsMonitor
     16 from pytorch_lightning.callbacks.early_stopping import EarlyStopping

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/base.py in <module>
     24 
     25 import pytorch_lightning as pl
---> 26 from pytorch_lightning.utilities.types import STEP_OUTPUT
     27 
     28 

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/__init__.py in <module>
     16 import numpy
     17 
---> 18 from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
     19 from pytorch_lightning.utilities.distributed import AllGatherGrad, rank_zero_info, rank_zero_only  # noqa: F401
     20 from pytorch_lightning.utilities.enums import (  # noqa: F401

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py in <module>
     27 
     28 if _TORCHTEXT_AVAILABLE:
---> 29     if _compare_version("torchtext", operator.ge, "0.9.0"):
     30         from torchtext.legacy.data import Batch
     31     else:

/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/imports.py in _compare_version(package, op, version, use_base_version)
     52     """
     53     try:
---> 54         pkg = importlib.import_module(package)
     55     except (ModuleNotFoundError, DistributionNotFound):
     56         return False

/opt/conda/lib/python3.8/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/opt/conda/lib/python3.8/site-packages/torchtext/__init__.py in <module>
      7 from . import datasets
      8 from . import utils
----> 9 from . import vocab
     10 from . import transforms
     11 from . import functional

/opt/conda/lib/python3.8/site-packages/torchtext/vocab/__init__.py in <module>
      9 )
     10 
---> 11 from .vocab_factory import (
     12     vocab,
     13     build_vocab_from_iterator,

/opt/conda/lib/python3.8/site-packages/torchtext/vocab/vocab_factory.py in <module>
      2 from typing import Dict, Iterable, Optional, List
      3 from collections import Counter, OrderedDict
----> 4 from torchtext._torchtext import (
      5     Vocab as VocabPybind,
      6 )

ImportError: /opt/conda/lib/python3.8/site-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKS0_PSo
```

**Comment by Nic-Ma** [comment] 2022-02-08 09:48
> Hi @Nic-Ma, `pytorch-lightning==1.5.10` will include the patch and should be released this week (tomorrow or in a few days).

Let's wait for the new PyTorch-Lightning release to totally fix this issue.

Thanks.

**Comment by wyli** [comment] 2022-02-13 23:57
would this be addressed by the current latest release?

**Comment by Nic-Ma** [comment] 2022-02-14 00:18
Hi @wyli ,

I will have a try the latest PyTorch-Lightning sometime this week.

Thanks.

**Comment by yiheng-wang-nv** [comment] 2022-02-14 12:43
Hi @wyli and @Nic-Ma ,

When using `pytorch-lightning==1.5.10`, do `import pytorch_lightning as pl` will not raise the error.

However, when I tested with `PyTorch Version 1.11.0a0+17540c5`, a new error is raised:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Input In [8], in <module>
      1 start = datetime.now()
      2 print('Training started at', start)
----> 3 trainer.fit(model=model, datamodule=data)
      4 print('Training duration:', datetime.now() - start)

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:740, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, train_dataloader, ckpt_path)
    735     rank_zero_deprecation(
    736         "`trainer.fit(train_dataloader)` is deprecated in v1.4 and will be removed in v1.6."
    737         " Use `trainer.fit(train_dataloaders)` instead. HINT: added 's'"
    738     )
    739     train_dataloaders = train_dataloader
--> 740 self._call_and_handle_interrupt(
    741     self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    742 )

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:685, in Trainer._call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    675 r"""
    676 Error handling, intended to be used only for main trainer function entry points (fit, validate, test, predict)
    677 as all errors should funnel through them
   (...)
    682     **kwargs: keyword arguments to be passed to `trainer_fn`
    683 """
    684 try:
--> 685     return trainer_fn(*args, **kwargs)
    686 # TODO: treat KeyboardInterrupt as BaseException (delete the code below) in v1.7
    687 except KeyboardInterrupt as exception:

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:777, in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    775 # TODO: ckpt_path only in v1.7
    776 ckpt_path = ckpt_path or self.resume_from_checkpoint
--> 777 self._run(model, ckpt_path=ckpt_path)
    779 assert self.state.stopped
    780 self.training = False

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1199, in Trainer._run(self, model, ckpt_path)
   1196 self.checkpoint_connector.resume_end()
   1198 # dispatch `start_training` or `start_evaluating` or `start_predicting`
-> 1199 self._dispatch()
   1201 # plugin will finalized fitting (e.g. ddp_spawn will load trained model)
   1202 self._post_dispatch()

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1279, in Trainer._dispatch(self)
   1277     self.training_type_plugin.start_predicting(self)
   1278 else:
-> 1279     self.training_type_plugin.start_training(self)

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py:202, in TrainingTypePlugin.start_training(self, trainer)
    200 def start_training(self, trainer: "pl.Trainer") -> None:
    201     # double dispatch to initiate the training loop
--> 202     self._results = trainer.run_stage()

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1289, in Trainer.run_stage(self)
   1287 if self.predicting:
   1288     return self._run_predict()
-> 1289 return self._run_train()

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1311, in Trainer._run_train(self)
   1308 if not self.is_global_zero and self.progress_bar_callback is not None:
   1309     self.progress_bar_callback.disable()
-> 1311 self._run_sanity_check(self.lightning_module)
   1313 # enable train mode
   1314 self.model.train()

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1375, in Trainer._run_sanity_check(self, ref_model)
   1373 # run eval step
   1374 with torch.no_grad():
-> 1375     self._evaluation_loop.run()
   1377 self.call_hook("on_sanity_check_end")
   1379 # reset logger connector

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py:145, in Loop.run(self, *args, **kwargs)
    143 try:
    144     self.on_advance_start(*args, **kwargs)
--> 145     self.advance(*args, **kwargs)
    146     self.on_advance_end()
    147     self.restarting = False

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py:110, in EvaluationLoop.advance(self, *args, **kwargs)
    105 self.data_fetcher = dataloader = self.trainer._data_connector.get_profiled_dataloader(
    106     dataloader, dataloader_idx=dataloader_idx
    107 )
    108 dl_max_batches = self._max_batches[dataloader_idx]
--> 110 dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
    112 # store batch level output per dataloader
    113 self.outputs.append(dl_outputs)

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py:140, in Loop.run(self, *args, **kwargs)
    136     return self.on_skip()
    138 self.reset()
--> 140 self.on_run_start(*args, **kwargs)
    142 while not self.done:
    143     try:

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py:86, in EvaluationEpochLoop.on_run_start(self, data_fetcher, dataloader_idx, dl_max_batches, num_dataloaders)
     83 self._data_fetcher = data_fetcher
     85 self._reload_dataloader_state_dict(data_fetcher)
---> 86 self._dataloader_iter = _update_dataloader_iter(data_fetcher, self.batch_progress.current.ready)

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py:121, in _update_dataloader_iter(data_fetcher, batch_idx)
    118 """Attach the dataloader."""
    119 if not isinstance(data_fetcher, DataLoaderIterDataFetcher):
    120     # restore iteration
--> 121     dataloader_iter = enumerate(data_fetcher, batch_idx)
    122 else:
    123     dataloader_iter = iter(data_fetcher)

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py:199, in AbstractDataFetcher.__iter__(self)
    197 self.dataloader_iter = iter(self.dataloader)
    198 self._apply_patch()
--> 199 self.prefetching(self.prefetch_batches)
    200 return self

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py:258, in DataFetcher.prefetching(self, prefetch_batches)
    256 for _ in range(prefetch_batches):
    257     try:
--> 258         self._fetch_next_batch()
    259     except StopIteration:
    260         break

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py:300, in DataFetcher._fetch_next_batch(self)
    298 data = self.on_fetch_start()
    299 with self.apply_profiler(f"fetch_next_{self.stage}_batch"):
--> 300     batch = next(self.dataloader_iter)
    301 self.fetched += 1
    302 self.on_fetch_end(batch, data)

File /opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py:530, in _BaseDataLoaderIter.__next__(self)
    528 if self._sampler_iter is None:
    529     self._reset()
--> 530 data = self._next_data()
    531 self._num_yielded += 1
    532 if self._dataset_kind == _DatasetKind.Iterable and \
    533         self._IterableDataset_len_called is not None and \
    534         self._num_yielded > self._IterableDataset_len_called:

File /opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py:570, in _SingleProcessDataLoaderIter._next_data(self)
    568 def _next_data(self):
    569     index = self._next_index()  # may raise StopIteration
--> 570     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    571     if self._pin_memory:
    572         data = _utils.pin_memory.pin_memory(data)

File /opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py:52, in _MapDatasetFetcher.fetch(self, possibly_batched_index)
     50 else:
     51     data = self.dataset[possibly_batched_index]
---> 52 return self.collate_fn(data)

File /opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/auto_restart.py:474, in _capture_metadata_collate(samples, dataset, default_collate)
    462 def _capture_metadata_collate(samples: List, dataset: Dataset, default_collate: Callable) -> Dict:
    463     """A collate function that adds the state dict of a :class:`CaptureIterableDataset` or
    464     :class:`CaptureMapDataset` used in the worker processes. This function gets executed within the worker
    465     processes. The structure will be:
   (...)
    472         }
    473     """
--> 474     data = default_collate(samples)
    475     if not isinstance(dataset, (CaptureIterableDataset, CaptureMapDataset)):
    476         return data

File /opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py:157, in default_collate(batch)
    155 elif isinstance(elem, collections.abc.Mapping):
    156     try:
--> 157         return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
    158     except TypeError:
    159         # The mapping type may not support `__init__(iterable)`.
    160         return {key: default_collate([d[key] for d in batch]) for key in elem}

File /opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py:157, in <dictcomp>(.0)
    155 elif isinstance(elem, collections.abc.Mapping):
    156     try:
--> 157         return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
    158     except TypeError:
    159         # The mapping type may not support `__init__(iterable)`.
    160         return {key: default_collate([d[key] for d in batch]) for key in elem}

File /opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py:157, in default_collate(batch)
    155 elif isinstance(elem, collections.abc.Mapping):
    156     try:
--> 157         return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
    158     except TypeError:
    159         # The mapping type may not support `__init__(iterable)`.
    160         return {key: default_collate([d[key] for d in batch]) for key in elem}

File /opt/conda/lib/python3.8/site-packages/torchio/data/image.py:746, in ScalarImage.__init__(self, *args, **kwargs)
    744     raise ValueError('Type of ScalarImage is always torchio.INTENSITY')
    745 kwargs.update({'type': INTENSITY})
--> 746 super().__init__(*args, **kwargs)

File /opt/conda/lib/python3.8/site-packages/torchio/data/image.py:161, in Image.__init__(self, path, type, tensor, affine, check_nans, reader, **kwargs)
    158     warnings.warn(message, DeprecationWarning)
    160 super().__init__(**kwargs)
--> 161 self.path = self._parse_path(path)
    163 self[PATH] = '' if self.path is None else str(self.path)
    164 self[STEM] = '' if self.path is None else get_stem(self.path)

File /opt/conda/lib/python3.8/site-packages/torchio/data/image.py:428, in Image._parse_path(self, path)
    426     return None
    427 elif self._is_paths_sequence(path):
--> 428     return [self._parse_single_path(p) for p in path]
    429 else:
    430     return self._parse_single_path(path)

File /opt/conda/lib/python3.8/site-packages/torchio/data/image.py:428, in <listcomp>(.0)
    426     return None
    427 elif self._is_paths_sequence(path):
--> 428     return [self._parse_single_path(p) for p in path]
    429 else:
    430     return self._parse_single_path(path)

File /opt/conda/lib/python3.8/site-packages/torchio/data/image.py:418, in Image._parse_single_path(path)
    415     raise RuntimeError(message)
    417 if not (path.is_file() or path.is_dir()):   # might be a dir with DICOM
--> 418     raise FileNotFoundError(f'File not found: "{path}"')
    419 return path

FileNotFoundError: File not found: "data"
```
for `torch==1.10.2`, there is no such error.

**Comment by yiheng-wang-nv** [comment] 2022-02-15 03:08
> 

Hi @Nic-Ma , I checked `torchio` yesterday, and the latest version also failed.

**Comment by yiheng-wang-nv** [comment] 2022-02-15 03:17
Hi @wyli , for the error you mentioned:
`ImportError: /opt/conda/lib/python3.8/site-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKS0_PSo`

It is due to the version of `torchtext` and `torch` mismatch. The current notebook tries to install `torch==1.10.2`, but does not change `torchtext` and `torchvision` at the same time.

Let me submit a PR to fix this issue, but we may still need to figure out the error I mentioned above later.

**Closed** 2022-02-15 07:57 UTC
