### ISSUE TITLE
Contributing Guidelines for MONAI Tutorials

### ISSUE THREAD

**Issue by finalelement** [Project-MONAI/tutorials#761] opened 2022-06-23 21:52 UTC
**Is your feature request related to a problem? Please describe.**
A set of contributing guidelines would be helpful for MONAI Tutorial as well, like we have for MONAI Core. For e.g it could begin with consisting formatting fixes and also the other list that are mentioned such as variable naming conventions etc.

**Describe the solution you'd like**
Just a contributing guidelines MD would be helpful

**Comment by wyli** [comment] 2022-09-01 13:35
just realised this is duplicate of https://github.com/Project-MONAI/tutorials/issues/118

**Closed by wyli** 2022-09-01 13:35 UTC
